### ISSUE TITLE
Method to programmatically close tooltip

### ISSUE THREAD

**Issue by bradyhigginbotham** [prscX/react-native-tooltips#5]
`clickToHide` is nice, but would like a way to have other components control visibility of the tooltip, i.e. toggling a checkbox immediately shows/hides an open tooltip.

**Comment by prscX** [comment]
Thanks @bradyhigginbotham for raising the enhancement request.

I have added new props: `dismiss` in order to close tooltip programmatically. Can you please install latest version [0.0.6](https://github.com/prscX/react-native-tooltips/releases/tag/v0.0.6) to verify the same.

Please let me know in case you face any issues.

Thanks
</ Pranav >
